Models/LocalReservation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarragoWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalReservation()
        {
            this.LocalRequirements = new HashSet<LocalRequirements>();
        }
    
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public int PersonsNumber { get; set; }
        public string Confirmation { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string UserObservation { get; set; }
        public string AdminObservation { get; set; }
        public double FinalPrice { get; set; }
        public string Status { get; set; }
    
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalRequirements> LocalRequirements { get; set; }
        public virtual User User { get; set; }
    }
}

Models/Requirements.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarragoWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requirements()
        {
            this.LocalRequirements = new HashSet<LocalRequirements>();
        }
    
        public int id { get; set; }
        public string ReqName { get; set; }
        public string Description { get; set; }
        public double Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalRequirements> LocalRequirements { get; set; }
    }
}

Controllers/RequirementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FarragoWebApp.Models;

namespace FarragoWebApp.Controllers
{
    public class RequirementsController : Controller
    {
        // GET: Requirements
        public ActionResult Index()
        {
            try
            {
                using (Farrago584Entities db = new Farrago584Entities())
                {
                    return View(db.Requirements.ToList());
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al mostrar Requerimientos Disponibles" + ex.Message);
                return View();
            }
        }
        public ActionResult RequirementList()
        {
            using (Farrago584Entities db = new Farrago584Entities())
            {
                List<Requirements> requirements = db.Requirements.ToList();
                RequirementList listRequirements = new RequirementList();
                foreach(var req in requirements)
                {
                    req.isChecked = true;
                }
                listRequirements.RequirementsList = requirements;
                return View(listRequirements);
            }
        }

        [HttpPost]
        public ActionResult RequirementList(RequirementList requirements)
        {
            //Modelo con errores
            try
            {
                using (Farrago584Entities db = new Farrago584Entities())
                {
                    int userId = (int)Session["userID"];
                    User user = db.User.Find(userId);
                    LocalReservation actualReservation = db.LocalReservation.Where(x => x.UserId == userId && x.Status == "P").ToList().LastOrDefault();
                    double price = 0;
                    foreach(var req in requirements.RequirementsList)
                    {
                        if (req.isChecked)
                        {
                            Requirements actualReq = db.Requirements.Find(req.id);
                            LocalRequirements atualLocalRequirement = new LocalRequirements();
                            price += req.Cost;
                            atualLocalRequirement.Requirement = actualReq.id;
                            atualLocalRequirement.LocalReservation = actualReservation.id;
                            db.LocalRequirements.Add(atualLocalRequirement);
                            db.SaveChanges();
                        }
                    }
                    actualReservation.FinalPrice = price;
                    db.SaveChanges();
                    return RedirectToAction("Index", "LocalReservation", new { area = "" });
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al registrar Lista de Requerimientos: " + ex.Message);
                return View(requirements);
            }
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FarragoWebApp.Models;

namespace FarragoWebApp.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            try
            {
                using (Farrago584Entities db = new Farrago584Entities())
                {
                    return View(db.User.ToList());
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al mostrar Usuarios " + ex.Message);
                return View();
            }
        }

        public ActionResult Details()
        {
            int userId = (int)Session["userID"];
            try
            {
                using (Farrago584Entities db = new Farrago584Entities())
                {
                    User user = db.User.Find(userId);
                   return View(user);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al mostrar Usuarios " + ex.Message);
                return View();
            }
        }

        public ActionResult UserProfile(int id)
        {
            try
            {
                using (Farrago584Entities db = new Farrago584Entities())
                {
                    User user = db.User.Find(id);
                    return View(user);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al mostrar Usuarios " + ex.Message);
                return View();
            }
        }

        public static string UserName(int UserId)
        {
            try
            {
                using (Farrago584Entities db = new Farrago584Entities())
                {
                    User user = db.User.Find(UserId);
                    return user.FullName;
                }
            }
            catch (Exception)
            {
                return "Error";
            }
        }

        public static void UserCounters(int userId, string action, bool flag)
        {
            try
            {
                using (Farrago584Entities db = new Farrago584Entities())
                {
                    User user = db.User.Find(userId);
                    if (!flag)
                    {
                        if (action == "R")
                        {
                            user.ReservationsNumber--;
                        }
                        if (action == "A")
                        {
                            user.AssistedNumber--;
                        }
                        if (action == "F")
                        {
                            user.FaultsNumber--;
                        }

                    }
                    else
                    {
                        if (action == "R")
                        {
                            user.ReservationsNumber++;
                        }
                        if (action == "A")
                        {
                            user.AssistedNumber++;
                        }
                        if (action == "F")
                        {
                            user.FaultsNumber++;
                        }

                    }
                    db.SaveChanges();
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult Register()
        {
            try
            {
                using (Farrago584Entities db = new Farrago584Entities())
                {
                    User user = new User();
                    user.BornDate = DateTime.Now;
                    return View(user);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error generar vista de Registro: " + ex.Message);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User user)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                if (user.Password != user.PasswordConfirmation)
                {
                    user.LoginErrorMessage = "La contraseña no coincide con la confirmación";
                    return View(user);
                }
                using (Farrago584Entities db = new Farrago584Entities())
                {
                    foreach (var client in db.User.ToList())
                    {
                        if (user.Username == client.Username)
                        {
                            user.LoginErrorMessage = "El el usuario ya se encuentra registrado. Ingrese un usuario diferente";
                            return View(user);
                        }
                        if (user.CellphoneNumber == client.CellphoneNumber)
                        {
                            user.LoginErrorMessage = "El número telefónico ingresado ya se encuentra registrado";
                            return View(user);
                        }
                        if (user.DNI == client.DNI)
                        {
                            user.LoginErrorMessage = "El DNI ya se encuentra registrado";
                            return View(user);
                        }
                        if (user.Email == client.Email)
                        {
                            user.LoginErrorMessage = "El Correo Electrónico ingresado ya se encuentra registrado";
                            return View(user);
                        }
                    }
                    user.ReservationsNumber = 0;
                    user.AssistedNumber = 0;
                    user.FaultsNumber = 0;
                    string born = user.BornDate.ToShortDateString();
                    user.BornDate = DateTime.Parse(born);
                    db.User.Add(user);
                    db.SaveChanges();
                    return View("Confirmation", user);                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error en el Registro: " + ex.Message);
                return View();
            }
        }

        public ActionResult Confirmation(User newUser)
        {
            try
            {
                using (Farrago584Entities db = new Farrago584Entities())
                {
                    User user = db.User.Find(newUser.id);
                    return View(user);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al mostrar Usuario " + ex.Message);
                return View();
            }
        }
    }
}

Views/LocalReservation/Admin.cshtml
@model IEnumerable<FarragoWebApp.Models.LocalReservation>

@{
    ViewBag.Title = "Reservaciones";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Reservas - Eventos</h2>
<table class="table" id="localReservationList">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PersonsNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Confirmation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                Cliente
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserObservation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AdminObservation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FinalPrice)
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    <h4>@Html.DisplayFor(modelItem => item.PersonsNumber)</h4>
                </td>
                <td>
                    @{
                        if (item.Confirmation == "N")
                        {
                            <span class="text-danger">No Confirmado</span>
                        }
                        else
                        {
                            <span class="text-success">Confirmado</span>
                        }
                    }
                </td>
                <td>
                    @{
                        if (item.Status == "P")
                        {
                            <span class="text-primary">Pendiente</span>
                        }
                        else if (item.Status == "C")
                        {
                            <span class="text-warning">Cancelado</span>
                        }
                        else if (item.Status == "F")
                        {
                            <span class="text-danger">No Asistida</span>
                        }
                        else
                        {
                            <span class="text-success">Asistido</span>
                        }
                    }
                </td>
                <td>
                    @Html.ActionLink(@FarragoWebApp.Controllers.UserController.UserName((int)item.UserId), "UserProfile", "User", new { id = item.UserId }, "")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserObservation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdminObservation)
                </td>
                <td>
                    S/@Html.DisplayFor(modelItem => item.FinalPrice).00
                </td>
                <td>
                    <table class="table">
                        <tr>
                            @{
                                if (item.Confirmation == "N")
                                {
                                    <td>@Html.ActionLink("Confirmar Reserva", "Confirm", "LocalReservation", new { id = item.id }, new { @class = "btn btn-success btn-sm" })</td>
                                }
                            }
                        </tr>
                        <tr>
                            @{
                                if (item.Status == "P")
                                {
                                    <td>@Html.ActionLink("Marcar Asistencia", "Asisted", "LocalReservation", new { id = item.id }, new { @class = "btn btn-primary btn-sm" })</td>
                                }
                            }
                        </tr>
                        <tr>
                            @{
                                if (item.Status == "P")
                                {
                                    <td>@Html.ActionLink("Marcar Falta", "Fault", "LocalReservation", new { id = item.id }, new { @class = "btn btn-danger btn-sm" })</td>
                                }
                            }
                        </tr>
                        <tr>
                            <td>@Html.ActionLink("Detalles", "Details", "LocalReservation", new { id = item.id }, new { @class = "btn btn-info btn-sm" })</td>
                        </tr>
                    </table>
                </td>
            </tr>
        }
    </tbody>

</table>

Views/LocalReservation/Asisted.cshtml
@model FarragoWebApp.Models.LocalReservation

@{
    ViewBag.Title = "Confirmar Reserva";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Registrar Asistencia de Evento</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 class="text-success">Registra la asistenacia de la reserva y escribe un comentario dirigido al cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.AdminObservation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminObservation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdminObservation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar Reservación" class="btn btn-primary" />
                @Html.ActionLink("Cancelar", "Dashboard", "Admin", new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Página Administrativa", "Dashboard", "Admin", new { @class = "btn btn-default" })
</div>

Views/LocalReservation/Confirm.cshtml
@model FarragoWebApp.Models.LocalReservation

@{
    ViewBag.Title = "Confirmar Reserva";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Registrar Confirmación de Evento</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 class="text-success">Registra la confirmación de la reserva y escribe un comentario dirigido al cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.AdminObservation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminObservation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdminObservation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar Reservación" class="btn btn-primary" />
                @Html.ActionLink("Cancelar", "Dashboard", "Admin", new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Página Administrativa", "Dashboard", "Admin", new { @class = "btn btn-default" })
</div>

Views/LocalReservation/Create.cshtml
@model FarragoWebApp.Models.LocalReservation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Solicitar reserva para Evento</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reserva de Local</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonsNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonsNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonsNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UserObservation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserObservation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserObservation, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Solicitar Reserva" class="btn btn-primary" />
                @Html.ActionLink("Cancelar", "Index", "", new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Mis Reservas", "Index", "", new { @class = "btn btn-default" })
    </div>

Views/LocalReservation/Details.cshtml
@model FarragoWebApp.Models.LocalReservation

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalle de Reservación</h2>

<div>
    <h4>Reservación para Evento RES  N°@Html.DisplayFor(model => model.id)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PersonsNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonsNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Confirmation)
        </dt>

        <dd>
            @{
                if (Model.Confirmation == "N")
                {
                    <span class="text-danger">No Confirmado</span>
                }
                else
                {
                    <span class="text-success">Confirmado</span>
                }
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdminId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserObservation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserObservation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdminObservation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminObservation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinalPrice)
        </dt>

        <dd>
            S/@Html.DisplayFor(model => model.FinalPrice).00
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @{
                if (Model.Status == "C")
                {
                    <span class="text-warning">Reserva Cancelada</span>
                }
                else if (Model.Status == "P")
                {
                    <span class="text-primary">Reserva Pendiente</span>
                }
                else if (Model.Status == "F")
                {
                    <span class="text-danger">Reserva no Asistida</span>
                }
                else
                {
                    <span class="text-success">Reserva Asistida</span>
                }
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RequirementsList)
        </dt>

        <dd>
            <div class="col-md-6">
                <table class="table">
                    <tr class="text-warning">
                        <td>Requerimiento</td>
                        <td>Descripción</td>
                        <td>Costo</td>
                    </tr>
                    @foreach (var req in Model.RequirementsList)
                    {
                        <tr>
                            <td>@req.ReqName</td>
                            <td>@req.Description</td>
                            <td>S/@req.Cost.00</td>
                        </tr>
                    }
                </table>
            </div>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Mis Reservas", "Index", "", new { @class = "btn btn-default" })
</p>

Views/LocalReservation/Edit.cshtml
@model FarragoWebApp.Models.LocalReservation

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Modificar mi Reserva</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Reserva N° @Model.id</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PersonsNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PersonsNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PersonsNumber, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.UserObservation, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserObservation, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserObservation, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-6">
        <table class="table table-hover">
            <tr class="text-success">
                <td>Requerimiento</td>
                <td>Descripción</td>
                <td>Costo</td>
                <td></td>
            </tr>
            @foreach (var req in Model.RequirementsList.ToList())
            {
                <tr>
                    <td>@req.ReqName</td>
                    <td>@req.Description</td>
                    <td>S/@req.Cost.00</td>
                </tr>
            }
            <tr><td>@Html.ActionLink("Solicitar Cambio de Requerimientos", "Requirements", new { id = Model.id }, new { @class = "btn btn-warning btn-sm" })</td></tr>
        </table>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Solicitar Cambio" class="btn btn-primary" />
            @Html.ActionLink("Cancelar", "Index", "", new { @class = "btn btn-danger" })
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Mis Reservas", "Index", "", new { @class = "btn btn-default" })
</div>

Views/LocalReservation/Requirements.cshtml
@model FarragoWebApp.Models.RequirementList

@{
    ViewBag.Title = "Lista de Requerimientos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Modificar Requerimientos para el Evento</h2>

@using (Html.BeginForm("RequirementList", "Requirements"))
{
    <div class="form-horizontal">
        <h4>Seleccione la lista de requerimientos que desee tener para su evento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Lista de Requerimientos Disponibles</label>
            <div class="col-md-4">
                <table class="table table-hover">
                    <tr class="text-success">
                        <td>Seleccionar</td>
                        <td>Requerimiento</td>
                        <td>Descripción</td>
                        <td>Costo</td>
                        <td></td>
                    </tr>
                    @for (int i = 0; i < Model.RequirementsList.Count; i++)
                    {
                        <tr>
                            <td>@Html.CheckBoxFor(m => Model.RequirementsList[i].isChecked)</td>
                            <td>@Model.RequirementsList[i].ReqName</td>
                            <td>@Model.RequirementsList[i].Description</td>
                            <td>S/@Model.RequirementsList[i].Cost.00</td>
                            <td>@Html.HiddenFor(m => Model.RequirementsList[i].id)</td>
                            <td>@Html.HiddenFor(m => Model.RequirementsList[i].Cost)</td>
                        </tr>
                    }
                </table>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Solicitar Lista" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>